doctrine:
    dbal:
        dbname: database
        host: localhost
        port: 3306
        user: root
        password:
        driver: pdo_mysql
        # if the url option is specified, it will override the above config
        url: mysql://root:@127.0.0.1:3306/main
        # the DBAL driverClass option
        driver_class: App\DBAL\MyDatabaseDriver
        # the DBAL driverOptions option
        options:
            foo: bar
        path: '%kernel.project_dir%/var/data/data.sqlite'
        memory: true
        unix_socket: /tmp/mysql.sock
        # the DBAL wrapperClass option
        wrapper_class: App\DBAL\MyConnectionWrapper
        charset: utf8mb4
        logging: '%kernel.debug%'
        server_version: '5.7'
        mapping_types:
            enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname: database
            host: localhost
            port: 3306
            user: root
            password:
            driver: pdo_mysql
            # if the url option is specified, it will override the above config
            url: mysql://root:@127.0.0.1:3306/main_test
            # the DBAL driverClass option
            driver_class: App\DBAL\MyDatabaseDriver
            # the DBAL driverOptions option
            options:
                foo: bar
            path: '%kernel.project_dir%/var/data/data.sqlite'
            memory: true
            unix_socket: /tmp/mysql.sock
            # the DBAL wrapperClass option
            wrapper_class: App\DBAL\MyConnectionWrapper
            charset: utf8mb4
            logging: '%kernel.debug%'
            platform_service: App\DBAL\MyDatabasePlatformService
            server_version: '5.7'
            mapping_types:
                enum: string
            types:
                custom: App\DBAL\MyCustomType

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
