vich_uploader:
    db_driver: orm

    mappings:
        articles_images:
            uri_prefix: '%articles_images%'
            upload_destination: '%kernel.project_dir%/public%articles_images%'
        events_images:
            uri_prefix: '%events_images%'
            upload_destination: '%kernel.project_dir%/public%events_images%'