<?php

// This file was generated by running "composer dump-env prod"

//return array (
//  'APP_ENV' => 'prod',
//  'APP_SECRET' => '20abf132d10ff3779a83b1c5dca28571',
//  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
//  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/main?sslmode=disable&charset=utf8mb4',
//);
