version: '3'

services:
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###> doctrine/doctrine-bundle ###




volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
